/*상품테이블*/
CREATE TABLE GOODS(
	GID CHAR(8) NOT NULL PRIMARY KEY,
    TITLE VARCHAR(300) NOT NULL,
    PRICE INT DEFAULT 0,
    MAKER VARCHAR(200),
    IMAGE VARCHAR(300),
    REGDATE DATETIME DEFAULT NOW()
);

/*사용자테이블*/
CREATE TABLE USERS(
	UID VARCHAR(20) NOT NULL PRIMARY KEY,
    UPASS VARCHAR(200) NOT NULL,
    UNAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS1 VARCHAR(300),
    ADDRESS2 VARCHAR(300),
	REGDATE DATETIME DEFAULT NOW(),
    PHOTO VARCHAR(200)
);


/*구매자정보테이블*/
CREATE TABLE PURCHASE(
	PID CHAR(13) NOT NULL PRIMARY KEY,
    UID VARCHAR(20) NOT NULL,
    RADDRESS1 VARCHAR(300),
    RADDRESS2 VARCHAR(300),
    RPHONE VARCHAR(20),
    PURDATE DATETIME DEFAULT NOW(), 
    STATUS INT DEFAULT 0, /*주문상태 0:상품준비중,1:배송준비중,2:배송완료,3.주문완료*/
    PURSUM INT DEFAULT 0, /*주문총액*/
    FOREIGN KEY(UID) REFERENCES USERS(UID)
);


/*주문상품테이블*/
CREATE TABLE ORDERS(
	OID INT AUTO_INCREMENT PRIMARY KEY,
    PID CHAR(13) NOT NULL,
    GID CHAR(8) NOT NULL,
    PRICE INT DEFAULT 0,
    QNT INT DEFAULT 0,
    FOREIGN KEY(PID) REFERENCES PURCHASE(PID),
    FOREIGN KEY(GID) REFERENCES GOODS(GID)
);



INSERT INTO USERS(UID, UPASS, UNAME, PHONE, ADDRESS1, ADDRESS2)
VALUES('blue', 'pass', '최블루', '010-1111-1111', '인천시 미추홀구 학익동', '디이스트 215-1801');
INSERT INTO USERS(UID, UPASS, UNAME, PHONE, ADDRESS1, ADDRESS2)
VALUES('green', 'pass', '김그린', '010-2222-2222', '인천시 남동구 선수촌공원로85', '1004동 501호');



SELECT * FROM ORDERS;


CREATE VIEW VIEW_PURCHASE AS
SELECT P.*, U.UNAME
FROM PURCHASE P, USERS U
WHERE P.UID=U.UID;

SELECT * FROM VIEW_PURCHASE WHERE UNAME='지나가는 행인';

SELECT * FROM VIEW_PURCHASE;

SELECT COUNT(*) FROM PURCHASE;

SELECT * FROM ORDERS WHERE PID='42da88ab-e8c4';

CREATE VIEW VIEW_ORDRS AS

SELECT O.*, TITLE, IMAGE
FROM ORDERS O, GOODS G
WHERE O.GID=G.GID;

SELECT * FROM VIEW_ORDRS;

ALTER TABLE USERS ADD ROLE INT DEFAULT 2;
SELECT * FROM USERS;

INSERT INTO USERS(UID, UPASS, UNAME, ROLE)
VALUE('manager', 'pass', '관리자', 1);


CREATE TABLE REVIEWS(
	RID INT AUTO_INCREMENT PRIMARY KEY,
    UID VARCHAR(20) NOT NULL,
    GID CHAR(8),
    REVDATE DATETIME DEFAULT NOW(),
    CONTENT TEXT,
    FOREIGN KEY(UID) REFERENCES USERS(UID),
    FOREIGN KEY(GID) REFERENCES GOODS(GID)
);

DROP TABLE REVIEWS;

DESC REVIEWS;


SELECT * FROM REVIEWS;



CREATE VIEW VIEW_REVIEWS AS

SELECT R.*, UNAME, PHOTO
FROM REVIEWS R, USERS U
WHERE R.UID=U.UID;

SELECT * FROM REVIEW_REVIEWS;